"""Create dashboard and dashboard_components table mismatch data type 

Revision ID: 836c92171a3b
Revises: 017a534fc005
Create Date: 2024-06-10 16:53:28.373841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '836c92171a3b'
down_revision: Union[str, None] = '017a534fc005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
   def upgrade() -> None:
    # Drop dashboard_components table first
    op.drop_table('dashboard_components')
    # Then drop dashboards table
    op.drop_table('dashboards', cascade=True)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_components',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('property', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('data_property', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('filter_property', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('dashboard_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name='dashboard_components_dashboard_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dashboard_components_pkey')
    )
    op.create_table('dashboards',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dashboards_pkey')
    )
    # ### end Alembic commands ###
